baseURL = "https://sld.res.ac/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Sine Lite Dies"
theme = "tale"
copyright = "Copyright (c) 2014-2018 Takezoe,Tomoaki"

[params]
  description = "Takezoe,Tomoakiのブログ"
  author = "Takezoe,Tomoaki"
  logo = "image/logo.jpg"

[taxonomies]
  category = "category"
  tag = "tag"

[[menu.global]]
  name = "このサイトについて"
  url = "/page/about/"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

