baseURL = "https://sld.res.ac/"
languageCode = "ja"
title = "Sine Lite Dies"
theme = "minimage"
copyright = "Copyright (c) 2018 Takezoe,Tomoaki"

[params]
  description = "This is desc"
  author = "Takezoe,Tomoaki"
  # logo = ""

[taxonomies]
  category = "category"
  tag = "tag"

[[menu.global]]
  name = "このサイトについて"
  url = "/page/about/"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

